#!/usr/bin/env bash
# Configure HAProxy
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000

frontend moalkhayat.tech
        bind 0:80
        default_backend moalkhayat.tech_backend

backend moalkhayat.tech_backend
        balance roundrobin
        server hostname hostIP:port check
        server 517184-web-01 54.234.63.45:80 check
        server 517184-web-02 18.233.62.93:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
