#!/usr/bin/env bash
#why u love me

varcrede()
{
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && varcrede' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'varcrede' SIGQUITgit
done
